version: '3.3'

services:
  # node-service-grpc:
  #   image: tuancr/poc-node-service:latest
  #   stdin_open: true
  #   tty: true
  #   env_file:
  #     - ./deploy/.node-gateway.env
  #   networks:
  #     - poc-network 
  #   restart: always
  # node-service-express:
  #   image: tuancr/poc-node-service:latest
  #   stdin_open: true
  #   tty: true
  #   env_file:
  #     - ./deploy/.node-gateway.env
  #   networks:
  #     - poc-network 
  #   restart: always
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - './deploy/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
      - './deploy/rabbitmq/init/:/var/lib/rabbitmq/init/'
    env_file:
      - ./deploy/rabbitmq/.example.env
    ports:
      - "5672:5672"
      - "15672:15672"
    command: sh /var/lib/rabbitmq/init/init.sh
    networks:
      - poc-network
  poc-machine-learning-consumer:
    restart: always
    image: tuancr/poc-machine-learning-service:latest
    stdin_open: true
    tty: true
    env_file:
      - ../deploy/.env
    networks:
      - poc-network
networks:
  poc-network:
    external: false
    name: poc-network
